steps:
### Build
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t asia-northeast3-docker.pkg.dev/$PROJECT_ID/fatclinic/was:$TAG_NAME .

### Publish
  - name: 'gcr.io/cloud-builders/docker'
    id: 'publish'
    entrypoint: 'bash'
    args:
     - '-c'
     - |
       docker push asia-northeast3-docker.pkg.dev/$PROJECT_ID/fatclinic/was:$TAG_NAME


### Deploy
  - id: 'deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
      - 'KUBECONFIG=/kube/config'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
          CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}
          PROJECT=$$(gcloud config get-value core/project)
          ZONE=${_CLOUDSDK_COMPUTE_ZONE}
          export PROJECT_ID=$PROJECT_ID
          export CLUSTER=gogle-cluster
          export ZONE=asia-northeast3

          gcloud container clusters get-credentials "$${CLUSTER}" \
            --project "$${PROJECT}" \
            --zone "$${ZONE}"  



          sed -i 's|asia-northeast3-docker.pkg.dev/exemplary-datum-362307/fatclinic/was:.*|asia-northeast3-docker.pkg.dev/exemplary-datum-362307/fatclinic/was:$TAG_NAME|' ./k8s/*.yaml
          
          kubectl get ns was || kubectl create ns was
          kubectl apply --namespace was --recursive -f ./k8s/
